### ISSUE TITLE
[for: Win64][on: Ubuntu 22.04] lensfun failed to build

### ISSUE THREAD

**Issue by li-yifei** [rdp/ffmpeg-windows-build-helpers#687] opened 2023-03-08 14:35 UTC
IMO it's better to track a certain tag of lensfun like `v0.3.3` rather than main branch bcs it seems broken.

Logs below
```
Scanning dependencies of target lensfun
[  6%] Generating build/timestamp
[ 25%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.obj
[ 25%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mount.cpp.obj
[ 25%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/cpuid.cpp.obj
[ 31%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.obj
[ 43%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color.cpp.obj
[ 43%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-coord-sse.cpp.obj
[ 50%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color-sse2.cpp.obj
[ 56%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/lens.cpp.obj
[ 62%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-coord.cpp.obj
[ 68%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color-sse.cpp.obj
[ 75%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-subpix.cpp.obj
[ 81%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.obj
[ 87%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/modifier.cpp.obj
[ 93%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-pc.cpp.obj
running build
running build_py
copying /somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/apps/lensfun/__init__.py -> build/lib/lensfun
[ 93%] Built target python-package
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp: In member function 'lfError lfDatabase::Load(const char*, const char*, size_t)':
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:826:27: error: 'locale_t' was not declared in this scope; did you mean '_locale_t'?
  826 |     auto loc = uselocale((locale_t) 0); // get current local
      |                           ^~~~~~~~
      |                           _locale_t
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:826:16: error: 'uselocale' was not declared in this scope; did you mean 'setlocale'?
  826 |     auto loc = uselocale((locale_t) 0); // get current local
      |                ^~~~~~~~~
      |                setlocale
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:827:27: error: 'LC_NUMERIC_MASK' was not declared in this scope; did you mean 'LC_NUMERIC'?
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                           ^~~~~~~~~~~~~~~
      |                           LC_NUMERIC
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:827:59: error: expected ')' before numeric constant
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                          ~                                ^~
      |                                                           )
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:827:17: error: 'newlocale' was not declared in this scope; did you mean 'setlocale'?
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                 ^~~~~~~~~
      |                 setlocale
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:858:5: error: 'freelocale' was not declared in this scope; did you mean '_free_locale'?
  858 |     freelocale(nloc);
      |     ^~~~~~~~~~
      |     _free_locale
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp: In member function 'lfError lfDatabase::Save(char*&, size_t&) const':
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:901:27: error: 'locale_t' was not declared in this scope; did you mean '_locale_t'?
  901 |     auto loc = uselocale((locale_t) 0); // get current local
      |                           ^~~~~~~~
      |                           _locale_t
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:901:16: error: 'uselocale' was not declared in this scope; did you mean 'setlocale'?
  901 |     auto loc = uselocale((locale_t) 0); // get current local
      |                ^~~~~~~~~
      |                setlocale
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:902:27: error: 'LC_NUMERIC_MASK' was not declared in this scope; did you mean 'LC_NUMERIC'?
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                           ^~~~~~~~~~~~~~~
      |                           LC_NUMERIC
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:902:59: error: expected ')' before numeric constant
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                          ~                                ^~
      |                                                           )
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:902:17: error: 'newlocale' was not declared in this scope; did you mean 'setlocale'?
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                 ^~~~~~~~~
      |                 setlocale
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/database.cpp:1144:5: error: 'freelocale' was not declared in this scope; did you mean '_free_locale'?
 1144 |     freelocale(nloc);
      |     ^~~~~~~~~~
      |     _free_locale
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/lens.cpp: In member function 'void lfLens::GuessParameters()':
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/lens.cpp:178:27: error: 'locale_t' was not declared in this scope; did you mean '_locale_t'?
  178 |     auto loc = uselocale((locale_t) 0); // get current local
      |                           ^~~~~~~~
      |                           _locale_t
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/lens.cpp:178:16: error: 'uselocale' was not declared in this scope; did you mean 'setlocale'?
  178 |     auto loc = uselocale((locale_t) 0); // get current local
      |                ^~~~~~~~~
      |                setlocale
make[2]: *** [libs/lensfun/CMakeFiles/lensfun.dir/build.make:78: libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/lens.cpp:179:27: error: 'LC_NUMERIC_MAS
' was not declared in this scope; did you mean 'LC_NUMERIC'?
  179 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                           ^~~~~~~~~~~~~~~
      |                           LC_NUMERIC
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/lens.cpp:179:59: error: expected ')' before numeric constant
  179 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                          ~                                ^~
      |                                                           )
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/lens.cpp:179:17: error: 'newlocale' was not declared in this scope; did you mean 'setlocale'?
  179 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                 ^~~~~~~~~
      |                 setlocale
/somewhere/to/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/libs/lensfun/lens.cpp:271:5: error: 'freelocale' was not declared in this scope; did you mean '_free_locale'?
  271 |     freelocale(nloc);
      |     ^~~~~~~~~~
      |     _free_locale
make[2]: *** [libs/lensfun/CMakeFiles/lensfun.dir/build.make:92: libs/lensfun/CMakeFiles/lensfun.dir/lens.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:133: libs/lensfun/CMakeFiles/lensfun.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by Biswa96** [comment] 2023-03-08 14:59
Duplicate of https://github.com/rdp/ffmpeg-windows-build-helpers/issues/686

There is a pending pull request in upstream. You can add the patch from there.

**Closed** 2023-04-14 06:28 UTC
