### ISSUE TITLE
ERROR: libbluray not found using pkg-config

### ISSUE THREAD

**Issue by Lazinezz** [rdp/ffmpeg-windows-build-helpers#267] opened 2017-10-16 02:05 UTC
Hi, tried compiling ffmpeg using rdp's current build script resulting with this "libbluray not found using pkg-config" error...need help with this pls...anyone?

/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc -Wl,--nxcompat,--dynamicbase -Wl,--high-entropy-va -Wl,--as-needed -Wl,--pic-executable,-e,mainCRTStartup -Wl,--image-base,0x140000000 -I/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include -L/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib -o /tmp/ffconf.067CZBqO/test.exe /tmp/ffconf.067CZBqO/test.o -lbluray -lxml2 -lfreetype -lgdi32
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x233): undefined reference to `gzopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x233): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x312): undefined reference to `gzdopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x312): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzdopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x5dc): undefined reference to `gzdopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x5dc): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzdopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0xbd4): undefined reference to `gzdopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0xbd4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzdopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0xcb4): undefined reference to `gzdopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0xcb4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzdopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x1567): undefined reference to `gzread'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x1567): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzread'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x2087): undefined reference to `gzwrite'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x2087): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzwrite'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x3e55): undefined reference to `gzclose'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x3e55): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzclose'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x4f2c): undefined reference to `gzdirect'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.text+0x4f2c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gzdirect'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.data+0x8): undefined reference to `gzopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xmlIO.o):xmlIO.c:(.rdata$.refptr.gzopen[.refptr.gzopen]+0x0): undefined reference to `gzopen'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x747): undefined reference to `lzma_code'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x747): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `lzma_code'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x7a6): undefined reference to `crc32'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x7a6): additional relocation overflows omitted from the output
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x81b): undefined reference to `inflate'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x934): undefined reference to `crc32'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0xb9e): undefined reference to `lzma_auto_decoder'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0xcb0): undefined reference to `lzma_properties_decode'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0xd1a): undefined reference to `inflateInit2_'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x120b): undefined reference to `inflateReset'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x1217): undefined reference to `crc32'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x1f15): undefined reference to `lzma_end'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(xzlib.o):xzlib.c:(.text+0x1f4b): undefined reference to `inflateEnd'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x233b): undefined reference to `libiconv_open'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x234d): undefined reference to `libiconv_open'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x23dc): undefined reference to `libiconv_open'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x2501): undefined reference to `libiconv_open'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x253b): undefined reference to `libiconv_close'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x2543): undefined reference to `libiconv_close'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x2557): undefined reference to `libiconv_open'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x2f11): undefined reference to `libiconv'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x3111): undefined reference to `libiconv'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x3486): undefined reference to `libiconv'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x3856): undefined reference to `libiconv'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x3b73): undefined reference to `libiconv'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x3ef1): more undefined references to `libiconv' follow
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x46dd): undefined reference to `libiconv_close'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x473c): undefined reference to `libiconv_close'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libxml2.a(encoding.o):encoding.c:(.text+0x48e5): undefined reference to `libiconv'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x316b): undefined reference to `png_create_read_struct'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x3181): undefined reference to `png_create_info_struct'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x31a4): undefined reference to `png_set_longjmp_fn'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x31ca): undefined reference to `png_destroy_read_struct'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x31f0): undefined reference to `png_set_read_fn'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x31fd): undefined reference to `png_read_info'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x323f): undefined reference to `png_get_IHDR'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x32d1): undefined reference to `png_destroy_read_struct'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x330a): undefined reference to `png_set_expand_gray_1_2_4_to_8'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x331d): undefined reference to `png_get_valid'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x3357): undefined reference to `png_set_interlace_handling'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x336b): undefined reference to `png_set_filler'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x3378): undefined reference to `png_read_update_info'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x33ba): undefined reference to `png_get_IHDR'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x33fb): undefined reference to `png_set_read_user_transform_fn'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x3463): undefined reference to `png_set_gray_to_rgb'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x3471): undefined reference to `png_set_packing'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x347f): undefined reference to `png_set_tRNS_to_alpha'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x348d): undefined reference to `png_set_strip_16'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x349e): undefined reference to `png_set_palette_to_rgb'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x34b6): undefined reference to `png_set_read_user_transform_fn'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x350f): undefined reference to `png_read_image'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x3528): undefined reference to `png_read_end'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x35c9): undefined reference to `png_get_error_ptr'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x35e4): undefined reference to `png_set_longjmp_fn'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x66c2): undefined reference to `png_get_io_ptr'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x66fa): undefined reference to `png_get_error_ptr'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x670a): undefined reference to `png_error'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x4c): undefined reference to `inflateEnd'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x122): undefined reference to `inflate'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x3b6): undefined reference to `inflateReset'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x66b): undefined reference to `inflateInit2_'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x922): undefined reference to `inflateReset'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x973): undefined reference to `inflateEnd'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0xa19): undefined reference to `inflateReset'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0xbbf): undefined reference to `inflateInit2_'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0xbd0): undefined reference to `inflate'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0xbdf): undefined reference to `inflateEnd'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0xc0a): undefined reference to `inflateEnd'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftbzip2.o):ftbzip2.c:(.text+0x2c): undefined reference to `BZ2_bzDecompressEnd'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftbzip2.o):ftbzip2.c:(.text+0xe0): undefined reference to `BZ2_bzDecompress'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftbzip2.o):ftbzip2.c:(.text+0x379): undefined reference to `BZ2_bzDecompressEnd'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftbzip2.o):ftbzip2.c:(.text+0x3c6): undefined reference to `BZ2_bzDecompressInit'
/home/linuxlite/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(ftbzip2.o):ftbzip2.c:(.text+0x61f): undefined reference to `BZ2_bzDecompressInit'
collect2: error: ld returned 1 exit status
ERROR: libbluray not found using pkg-config

**Comment by hydra3333** [comment] 2017-10-16 05:13
The ffmpeg maintainers changed the way the ffmpeg configure works.  It's broken pending "upstream" software dependency maintainers adjust their build systems to be "correct" in specifying the libraries they link to.

ffmpeg git changed something like "extralibs no longer being global after this merge" which broke lots of the building process ... hence one interim a workaround could be add back in lots of "--extra-libs=" to temporarily fix it.   As soon as that's done then we can probably remove the lots of brute-force "--extra-libs=" which make this interim build work.

For some commonly specified dependencies, you could add something like a variation of this to the "configure" statement in the script.
```
    # 2017.10.14 - START add this for various errors per https://patchwork.ffmpeg.org/patch/5540/ - they removed from being extralibs being global any more
    #config_options+=" --extra-libs=-lpthread" # is global again 2017.10.15
    #config_options+=" --extra-libs=-lm" # is global again 2017.10.15
    config_options+=" --extra-libs=-lcrypt32"
    config_options+=" --extra-libs=-lshlwapi"
    config_options+=" --extra-libs=-lstdc++"
    config_options+=" --extra-libs=-lass"
    config_options+=" --extra-libs=-lfontconfig"
    config_options+=" --extra-libs=-lexpat"
    config_options+=" --extra-libs=-lfribidi"
    config_options+=" --extra-libs=-lfreetype"
    config_options+=" --extra-libs=-lharfbuzz"
    config_options+=" --extra-libs=-lbz2"
    config_options+=" --extra-libs=-llzma"
    config_options+=" --extra-libs=-liconv"
    config_options+=" --extra-libs=-lcdio"
    config_options+=" --extra-libs=-lcdio_paranoia"
    config_options+=" --extra-libs=-lz"
    config_options+=" --extra-libs=-lpsapi" # dlfcn [frei0r?] requires this, has no .pc file should put in frei0r.pc? ...
    config_options+=" --extra-libs=-lspeexdsp" # libebur :|
    config_options+=" --extra-libs=-lgdi32"
    #config_options+=" --extra-libs=-luser32"
    config_options+=" --extra-libs=-lwinmm"
#    export LDFLAGS="$LDFLAGS -l-lstdc++ ... etc "
    # 2017.10.14 - END add this for various errors per https://patchwork.ffmpeg.org/patch/5540/ - they removed from being extralibs being global any more

```

**Comment by rdp** [comment] 2017-10-16 05:44
If you nuke sandbox dis it come back?

**Comment by Lazinezz** [comment] 2017-10-16 07:14
yes rdp same repeated error....nuked sandbox, tried with older versions of mingw64 and newer/older versions of gcc and still same error occurred.
hydra333, how u do that? and thanks much both fer replying.

**Comment by hydra3333** [comment] 2017-10-16 07:53
> how u do that?
Badly.  brute force and a rocketful of ignorance.
I see you're adept at modifying scripts https://github.com/rdp/ffmpeg-windows-build-helpers/issues/209 and so should have no trouble locating "build_ffmpeg" and inserting a variation in there.  If you use different dependencies, more or less, suggest go from there.  And, do whatever rdp says :)

**Comment by Lazinezz** [comment] 2017-10-16 08:02
hmm..yeh i get what u mean and after reading the discussions in that patchwork ffmpeg link, i think i understand it..i think. lol so yeh will try to do as suggested and update later,thx.

**Comment by Reino17** [comment] 2017-10-16 21:35
This issue can fixed by temporarily updating libbluray's pc-file
```
prefix=/cygdrive/[...]
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libbluray
Description: library supporting Blu-ray playback
Version: 1.0.1
Libs: -L${libdir} -lbluray
Libs.private:  -L/cygdrive/[...]/lib -lxml2 -L/cygdrive/[...]/lib
-lfreetype -lgdi32
Cflags: -I${includedir}
```
...into:
```
`prefix=/cygdrive/[...]
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libbluray
Description: library supporting Blu-ray playback
Version: 1.0.1
Requires: libxml-2.0, freetype2
Libs: -L${libdir} -lbluray
Libs.private: -lgdi32
Cflags: -I${includedir}
```

Lazinezz, could you please wrap your log in your first post in backticks to create a codeblock? Right now it's rather messy!

**Comment by Reino17** [comment] 2017-10-17 20:21
...[and the issue is fixed in libbluray](https://mailman.videolan.org/pipermail/libbluray-devel/2017-October/002857.html).

**Comment by rdp** [comment] 2017-10-19 05:09
closing, hopefully fixed upstream thanks for the tips all.

**Closed by rdp** 2017-10-19 05:09 UTC

**Comment by ufgkirk** [comment] 2019-09-04 01:37
Issue appears fixed, I was able to compile on a vanilla Ubuntu 18 installation after installing the dependencies specified by the script's output without any problems this time. :)  Thank you!

**Comment by sproott** [comment] 2021-12-29 23:39
@rdp Hello, this problem has happened to me today while using the current version of this script. I was building the Win64 executable and it crashed with `ERROR: libbluray not found using pkg-config`.

If any additional info is needed, let me know.

**Comment by rdp** [comment] 2022-01-03 23:25
config.log file?

**Comment by sproott** [comment] 2022-01-08 19:13
https://gist.github.com/sproott/7ad3b5de81c9f1b7941ce2ecb10ff4fa

**Comment by xuleiisprogrammer** [comment] 2022-06-17 09:47
if libbluray is not  necessary， set --disable-libbluray in ffmpeg.cmake

**Comment by SmoochySix4** [comment] 2022-07-14 03:28
I had to remove all three to get a build to work.

**Comment by rdp** [comment] 2022-07-15 03:54
Also related to #497 not sure why I can't repro it tho...

**Comment by nschlia** [comment] 2023-09-01 17:28
Same here, had to remove fontconfig, freetype2, and  libbluray. Next git pull overwrote my changes, though, and trouble started over. And, yes, deleted the sandbox. Twice. Fiddled about with the build parameters. All up to no avail.

Wouldn't it be possible to add command line parameters to disable anything, or a configuration file?
