### ISSUE TITLE
building toolchain fails when installing binutils when linking with ldlex.c:3342: undefined reference to `yywrap'

### ISSUE THREAD

**Issue by DragonMorkeleb** [rdp/ffmpeg-windows-build-helpers#201] opened 2017-01-30 23:38 UTC
_NOTE: This issue was previously named "building cross compiler on windows fails when downloading mingw-w64" but it was changed since this issue was adressed easily, but now another snag showed up.._

I got your scripts from master.zip just now and ran build_locally_with_various_option_prompts.bat
When it started to build the cross compiler this failed when downloading mingw-w64:

```
building win64 x86_64 cross compiler...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 77364  100 77364    0     0  81027      0 --:--:-- --:--:-- --:--:--  108k
[1/54]: Downloading config.guess... done
[2/54]: Downloading mingw-w64...       1 [main] git 9740 child_info_fork::abort: C:\apps\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_b
uilds\cygwin_local_install\bin\cygcrypto-1.0.0.dll: Loaded to different address: parent(0xC10000) != child(0xCC0000)
error

See build.log for more details.
failure building 64 bit gcc? recommend nuke sandbox (rm -rf sandbox) and start over...
done with local build...check output above to see if successfull..
if not successful you might try re running the script, it "should" pick up where it left off.

if you want more advanced configuration (like building mplayer or mp4box, 10-bit, etc)
open C:\apps\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds\cygwin_local_install\cygwin.bat
(which sets up the path for you)
then cd to C:\apps\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds and run the script manually yourself with -h
like $ cd /cygdrive/c/.../ffmpeg_local_builds $ ./cross_compile_ffmpeg.sh -h
running the script, it "should" pick up where it left off.

if you want more advanced configuration (like building mplayer or mp4box, 10-bit, etc)
open C:\apps\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds\cygwin_local_install\cygwin.bat
(which sets up the path for you)
then cd to C:\apps\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds and run the script manually yourself with -h
like $ cd /cygdrive/c/.../ffmpeg_local_builds $ ./cross_compile_ffmpeg.sh -h
```

I am running this on windows 10 on a normal console.
This happens for both the win32 and the win64 cross compiler, since it both cases it tries to get mingw-w64.
Any Ideas?

Btw, several months ago I ran your script on linux and after some initial hitches (I created another issue which you fixed) it compiled properly.
Since I now want to try around with envenc however and I don't see anything about nvenc being supported when cross-compiling on linux in your script I tried on windows.

**Comment by rdp** [comment] 2017-01-30 23:43
update windows and reboot?
https://github.com/babun/babun/issues/477

**Comment by DragonMorkeleb** [comment] 2017-01-30 23:44
I shall try.

**Comment by DragonMorkeleb** [comment] 2017-01-31 10:59
Restarting solved the download issue, now building binutils fails:

```
make[4]: Nothing to be done for 'install'.
make[4]: Leaving directory '/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld/po'
make[4]: Entering directory '/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld'
/bin/sh ../../../source/binutils-2.26.1/ld/../ylwrap ../../../source/binutils-2.26.1/ld/ldlex.l lex.yy.c ../../../source/binutils-2.26.1/ld/ldlex.c -- flex  
gcc -DHAVE_CONFIG_H -I. -I../../../source/binutils-2.26.1/ld  -I. -I../../../source/binutils-2.26.1/ld -I../bfd -I../../../source/binutils-2.26.1/ld/../bfd -I../../../source/binutils-2.26.1/ld/../include  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=FALSE -DELF_SHLIB_LIST_OPTIONS=FALSE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -MT ldlex-wrapper.o -MD -MP -MF .deps/ldlex-wrapper.Tpo -c -o ldlex-wrapper.o ../../../source/binutils-2.26.1/ld/ldlex-wrapper.c 
mv -f .deps/ldlex-wrapper.Tpo .deps/ldlex-wrapper.Po
/bin/sh ./libtool --tag=CC   --mode=link gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=FALSE -DELF_SHLIB_LIST_OPTIONS=FALSE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2  -Wl,--stack,12582912 -o ld-new.exe ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o ei386pe.o deffilep.o pe-dll.o ../bfd/libbfd.la ../libiberty/libiberty.a  
libtool: link: gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=FALSE -DELF_SHLIB_LIST_OPTIONS=FALSE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -Wl,--stack -Wl,12582912 -o ld-new.exe ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o ei386pe.o deffilep.o pe-dll.o  ../bfd/.libs/libbfd.a -L/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/zlib -lz ../libiberty/libiberty.a
ldlex-wrapper.o: In function `yylex':
/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld/../../../source/binutils-2.26.1/ld/ldlex.c:3342: undefined reference to `yywrap'
ldlex-wrapper.o: In function `input':
/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld/../../../source/binutils-2.26.1/ld/ldlex.c:3645: undefined reference to `yywrap'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:1088: ld-new.exe] Error 1
make[4]: Leaving directory '/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld'
make[3]: *** [Makefile:1713: install-recursive] Error 1
make[3]: Leaving directory '/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld'
make[2]: *** [Makefile:1877: install] Error 2
make[2]: Leaving directory '/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld'
make[1]: *** [Makefile:7228: install-ld] Error 2
make[1]: Leaving directory '/cygdrive/c/apps/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32'
make: *** [Makefile:2244: install] Error 2
```

I'll try from scratch just to be sure, now

**Comment by DragonMorkeleb** [comment] 2017-01-31 11:50
UPDATE: I deleted everything, downloaded the master again and started from scratch, and the error came up again.

**Comment by rdp** [comment] 2017-01-31 14:46
the yywrap one?

**Comment by DragonMorkeleb** [comment] 2017-01-31 17:00
Yes.

**Comment by charlie460** [comment] 2017-02-01 03:49
Getting the same yywrap error trying to build within Cygwin on Windows too.

**Comment by DragonMorkeleb** [comment] 2017-02-01 14:35
@rdp: since the error occurrs in the script from zeranoe, does it make sense asking on his forum about this issue, or do you want to look at it?

I am afraid I am not experienced enough to make good progress on tracking down and fixing the issue myself (don't know how make scripts work in detail and how to modify something, like changing parameters).
Since it appears the versions used for the toolchain are specified releases and the script version 3.6.7 has been out since august 2015 I assume those scripts are solid, so maybe something has changed in the versions of packages downloaded by cygwin?

**Comment by rdp** [comment] 2017-02-01 18:50
I know the cygwin build worked for me just a few days ago...will try it
again though :)

**Comment by thoth23** [comment] 2017-02-09 04:41
I'm new to ffmpeg-windows-build-helpers and havent messed with ffmpeg in a couple of years but the past couple of days I had downloaded hoping the scripts would help with the build but I'm getting:

   /source/binutils-2.26.1/ld/ldlex.c:3645: undefined reference to `yywrap' when Installing binutils...

I'm running Win10(amd64) and have a seperate working and recently updated installation of Cygwin64.

**Comment by rdp** [comment] 2017-02-10 07:21
I'm still chasing that one, I get it in cygwin but not linux oddly...

**Comment by thoth23** [comment] 2017-02-10 09:15
Okay, seemed that my installation interference and resulting failure may have been due to Windows Defender popping its head up in the background even though I was certain it was off. Turned it off and shut all other apps (especially antimalware/antivirus) down just to be safe and tried again. 20+ hours later (I was running build_locally_with_various_option_prompts.bat with both 32 and 64 bit with no GNU) and all preliminary tests support it worked!

**Comment by DragonMorkeleb** [comment] 2017-02-27 10:36
I tried again and disabled virus and malware (including checking windows defender) and I still get the same error.

How can I make sure that some such program is not the culprit?

**Comment by rdp** [comment] 2017-03-07 00:30
care to try again with the latest for me?

**Comment by DragonMorkeleb** [comment] 2017-03-08 14:42
Ok, ill do so today...

Am 07.03.2017 1:30 vorm. schrieb "Roger Pack" <notifications@github.com>:

**Comment by jantenhove** [comment] 2017-03-09 11:50
I have the same problem. Just downloaded the latest master.zip, removed sandbox folder and ran the options bat. Still fails with the `undefined reference to `yywrap'` error.
Windows Defender was disabled, rebooted the computer prior to the build.
#206 has the same problem.

The solution offered in some topics is to compile -lfl option, but that has to be done in the zeranoe script i guess.

**Comment by clicit** [comment] 2017-03-09 12:12
Same problem here: undefined reference toyywrap.
Also no success with disabling antivirus software and restarting..

**Comment by rdp** [comment] 2017-03-09 17:17
appears the binutils failure is actually <drum roll please> a bug in flex itself.

https://github.com/westes/flex/issues/154

so version 2.6.3 is "bad" as it were.  If you can revert to a previous package or "build from git master" that might be some possibilities [?]

Oddly I could reproduce this on cygwin but not OS X/hombrew but it's probably just different versions of flex...

**Comment by ajbeaven** [comment] 2017-03-12 11:03
Sorry, could you please clarify (to the noobs among us) how one might go about using a previous/master build of flex? I see some code that is potentially relevant in a file called `setup.ini` but am not confident enough to go playing around with that without direction.

**Comment by DeadSix27** [comment] 2017-03-12 11:16
@ajbeaven what  OS are you compiling on?

**Comment by ajbeaven** [comment] 2017-03-12 11:19
Windows 10 x64 running `build_locally_with_various_option_prompts.bat` to build both 32 and 64 bit versions of ffmpeg.

**Comment by DeadSix27** [comment] 2017-03-12 11:34
@ajbeaven https://cygwin.com/cgi-bin2/package-grep.cgi?grep=flex&arch=x86_64
there are 2  flex packages by cygwin for win64 flex-2.6.1-1 and flex-2.6.3-1 
not sure where the paths are that the windows script makes.

I always use my Ubuntu HomeServer and recommend using this script in a Linux VM.

But ye, try to search for the flex folder and replace it with one of the versions i mentioned above, depending on which is newer or older. ( if so )

Thats all I can think of, idk what @rdp meant by "master build", doubt he means you shall compile your own windows version of it. lol

**Comment by ajbeaven** [comment] 2017-03-12 12:04
@DeadSix27 thanks so much! Will try this out in the morning :)

**Comment by DeadSix27** [comment] 2017-03-12 20:00
@ajbeaven good to hear!

**Comment by DragonMorkeleb** [comment] 2017-03-14 23:32
I can confirm that the steps described by ajbeaven fixes the issue and I could compile everything properly.

**Comment by clicit** [comment] 2017-03-15 13:00
Hello,

unfortunately I had no success until now. But maybe I’m doing something wrong.. ?

I downloaded the flex-2.6.1-1 from somewhere but now what exactly do I need to do with it?

If I just replace the flex-2.6.3-1.tar.xy file the same error occurs.

 

My system: Win 8.1 x64

 

Many thanks!

Best regards,

christoph

 

 

Von: Hagen [mailto:notifications@github.com] 
Gesendet: Sonntag, 12. März 2017 12:34
An: rdp/ffmpeg-windows-build-helpers <ffmpeg-windows-build-helpers@noreply.github.com>
Cc: clicit <clic@clicit.at>; Comment <comment@noreply.github.com>
Betreff: Re: [rdp/ffmpeg-windows-build-helpers] building toolchain fails when installing binutils when linking with ldlex.c:3342: undefined reference to `yywrap' (#201)

 

@ajbeaven <https://github.com/ajbeaven>  https://cygwin.com/cgi-bin2/package-grep.cgi?grep=flex <https://cygwin.com/cgi-bin2/package-grep.cgi?grep=flex&arch=x86_64> &arch=x86_64
there are 2 flex packages by cygwin for win64 flex-2.6.1-1 and flex-2.6.3-1
not sure where the paths are that the windows script makes.

I always use my Ubuntu HomeServer and recommend using this script in a Linux VM.

But ye, try to search for the flex folder and replace it with one of the versions i mentioned above, depending on which is newer or older. ( if so )

Thats all I can think of, idk what @rdp <https://github.com/rdp>  meant by "master build", doubt he means you shall compile your own windows version of it. lol

**Comment by jantenhove** [comment] 2017-03-15 13:21
You have to extract the two files mentioned by @ajbeaven in the flex-2.6.1-1.tar.xz archive (I used 7-Zip). Afterwards delete the sandbox directory and rebuild.

**Comment by clicit** [comment] 2017-03-16 07:35
great thanks that worked! didn't get @ajbeaven 's post via email ..

**Comment by jpham986** [comment] 2017-03-23 01:35
When I try ffmpeg build - it complaints about GCC version - do we need to
get thelatest ?


$ ./cross_compile_ffmpeg.sh --gcc-cpu-count=24 --disable-nonfree=n -a
--build-ffmpeg-static=y
Wed, Mar 22, 2017 6:31:37 PM
     ##################### Welcome ######################
  Welcome to the ffmpeg cross-compile builder-helper script.
  Downloads and builds will be installed to directories within
/cygdrive/g/ffmpeg_work/f9/bhelper/native_build/windows/ffmpeg_local_builds/sandbox
  If this is not ok, then exit now, and cd to the directory where you'd
  like them installed, then run this script again from there.
  NB that once you build your compilers, you can no longer rename/move
  the sandbox directory, since it will have some hard coded paths in there.
  You can, of course, rebuild ffmpeg from within it, etc.
starting to download and build cross compile version of gcc [requires
working internet access] with thread count 24...

building win32 cross compiler...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100 77346  100 77346    0     0  94264      0 --:--:-- --:--:-- --:--:--
129k

Error, "4.9.3" is not a valid option for --gcc-ver. The valid options are:
6.3.0 4.9.4 svn

aba@zinger
/cygdrive/g/ffmpeg_work/f9/bhelper/native_build/windows/ffmpeg_local_builds

**Comment by rdp** [comment] 2017-03-23 04:57
Are you using the latest? It should be at 4.9.4...

**Comment by jpham986** [comment] 2017-03-23 07:33
trying with the latest

die in [2/54]: installing binutils...error

would be nice if it says what sort of error

===================================================

Thu, Mar 23, 2017 12:31:11 AM
     ##################### Welcome ######################
  Welcome to the ffmpeg cross-compile builder-helper script.
  Downloads and builds will be installed to directories within
/cygdrive/g/ffmpeg_work/f10/bhelper/native_build/windows/ffmpeg_local_builds/sandbox
  If this is not ok, then exit now, and cd to the directory where you'd
  like them installed, then run this script again from there.
  NB that once you build your compilers, you can no longer rename/move
  the sandbox directory, since it will have some hard coded paths in there.
  You can, of course, rebuild ffmpeg from within it, etc.
Would you like to include non-free (non GPL compatible) libraries, like
many high quality aac encoders [libfdk_aac]
The resultant binary may not be distributable, but can be useful for
in-house use. Include these non-free-license libraries [y/N]?y
What version of MinGW-w64 would you like to build or update?
  1. Both Win32 and Win64
  2. Win32 (32-bit only)
  3. Win64 (64-bit only)
  4. Exit
Input your choice [1-4]: 3
starting to download and build cross compile version of gcc [requires
working internet access] with thread count 28...

building win64 x86_64 cross compiler...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100 77346  100 77346    0     0   175k      0 --:--:-- --:--:-- --:--:--
393k
[1/54]: Downloading config.guess... done
MinGW-w64 is already the latest version, continue with the build anyway?
You can set this option with: '--allow-overwrite', see '--help' for more
information. [y/n]: y
[2/54]: Installing binutils... error

See build.log for more details.
failure building 64 bit gcc? recommend nuke sandbox (rm -rf sandbox) and
start over...

**Comment by jpham986** [comment] 2017-03-23 08:25
looking at build.log

/bin/sh ./libtool --tag=CC   --mode=link gcc -W -Wall -Wstrict-prototypes
-Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=FALSE
-DELF_SHLIB_LIST_OPTIONS=FALSE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2
-Wl,--stack,12582912 -o ld-new
.exe ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o
ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o
ldbuildid.o ei386pep.o ei386pe.o deffilep.o pep-dll.o pe-dll.o ../bfd/
libbfd.la ../libiberty/libiberty.a
libtool: link: gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes
-Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=FALSE
-DELF_SHLIB_LIST_OPTIONS=FALSE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2
-Wl,--stack -Wl,12582912 -o ld-new.exe ldgram.o ldlex-wra
pper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o
ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o ei386pep.o
ei386pe.o deffilep.o pep-dll.o pe-dll.o  ../bfd/.libs/libbfd.a
-L/cygdrive/g/ffmpeg_work/f10/bhelper/native_buil
d/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/x86_64-w64-mingw32/zlib
-lz ../libiberty/libiberty.a
ldlex-wrapper.o: In function `yylex':
/cygdrive/g/ffmpeg_work/f10/bhelper/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/x86_64-w64-mingw32/ld/../../../source/binutils-2.27/ld/ldlex.c:3352:
undefined reference to `yywrap'
ldlex-wrapper.o: In function `input':
/cygdrive/g/ffmpeg_work/f10/bhelper/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/x86_64-w64-mingw32/ld/../../../source/binutils-2.27/ld/ldlex.c:3655:
undefined reference to `yywrap'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:1143: ld-new.exe] Error 1
make[4]: Leaving directory
'/cygdrive/g/ffmpeg_work/f10/bhelper/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/x86_64-w64-mingw32/ld'
make[3]: *** [Makefile:1780: install-recursive] Error 1

**Comment by rdp** [comment] 2017-03-23 15:28
Yeah it's a faulty version of flex unfortunately.

**Comment by jpham986** [comment] 2017-03-23 19:25
>/cygdrive/g/ffmpeg_work/f10/bhelper/native_build/windows/
ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/
build/x86_64-w64-mingw32/ld/../../../source/binutils-2.27/ld/ldlex.c:3655:
undefined reference to `yywrap'

I did some search

add -lfl at the end instead of beginning. Alternatively, if you don't want
to use the library, just #define *yywrap*() 1 in your .l file, or provide a
*yywrap*() method that returns 1. Use gcc lex.yy.c -ll . Otherwise it will
yield an *undefined reference to yywrap* .Dec 26, 2012

**Comment by rdp** [comment] 2017-06-21 17:36
OK appears this is finally working with the new(er) version of flex and cygwin has the newer version of flex too, so closing for now, thanks all!

**Closed by rdp** 2017-06-21 17:36 UTC
