### ISSUE TITLE
Build problems with Ubuntu in WSL

### ISSUE THREAD

**Issue by H41Ri0** [rdp/ffmpeg-windows-build-helpers#704] opened 2023-07-18 16:44 UTC
```
/home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libSvtAv1Enc.a(EbSourceBasedOperationsProcess.c.obj):EbSourceBasedOperationsProcess.c:(.rdata+0x80): multiple definition of `AV1_VAR_OFFS'; /home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(encodeframe.c.obj):encodeframe.c:(.rdata+0x560): first defined here
/home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libSvtAv1Enc.a(EbSourceBasedOperationsProcess.c.obj):EbSourceBasedOperationsProcess.c:(.rdata+0x80): multiple definition of `AV1_VAR_OFFS'; /home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(encodeframe.c.obj):encodeframe.c:(.rdata+0x560): first defined here
/home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libSvtAv1Enc.a(EbSourceBasedOperationsProcess.c.obj):EbSourceBasedOperationsProcess.c:(.rdata+0x80): multiple definition of `AV1_VAR_OFFS'; /home/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(encodeframe.c.obj):encodeframe.c:(.rdata+0x560): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:133: ffprobe_g.exe] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make: *** [Makefile:133: ffplay_g.exe] Error 1
collect2: error: ld returned 1 exit status
make: *** [Makefile:133: ffmpeg_g.exe] Error 1
```

The argument is `. /cross_compile_ffmpeg.sh --disable-nonfree=n`

**Comment by 0Ky** [comment] 2023-07-20 06:43
This seems to be a duplicate of issue #703 that I already posted.

**Comment by rdp** [comment] 2024-01-24 06:12
OK I am unable to repro this (anymore?) so I am hoping something got fixed upstream, please reopen if not, thanks!

**Closed by rdp** 2024-01-24 06:12 UTC
