### ISSUE TITLE
Build fails due to crippled configure

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#147] opened 2016-07-29 11:48 UTC
Two days ago the build started to fail because "make install" of ffmpeg no longer goes to the sandbox.

The old configure command was:

>  ./configure --arch=x86 --target-os=mingw32 --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- --pkg-config=pkg-config --disable-w32threads --enable-libsoxr --enable-fontconfig --enable-libass --enable-libbluray --enable-iconv --enable-libtwolame --extra-cflags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --enable-decklink --extra-libs=-loleaut32  --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-libfreetype --enable-libopus --enable-bzlib --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --enable-libgme --enable-dxva2 --enable-avisynth --enable-gray --enable-libopenh264 --enable-nvenc --enable-libebur128 --enable-netcdf  --enable-libflite --enable-lzma --enable-libsnappy --enable-libzimg --enable-gpl --enable-libx264 --enable-libx265 --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libxavs --enable-libxvid --enable-libmfx --extra-libs=-lpsapi --extra-libs=-lspeexdsp --extra-cflags=-mtune=core2 --extra-cflags=-O3 --enable-static --disable-shared  --prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --enable-nonfree --enable-libfdk-aac --disable-libfaac  --enable-runtime-cpudetect 
 
Tow days ago it shrunk to this:
 
>  ./configure --arch=x86 --target-os=mingw32 --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- --pkg-config=pkg-config --disable-w32threads --enable-librubberband --enable-gpl

The command line:

> ./cross_compile_ffmpeg.sh --disable-nonfree=n --build-ffmpeg-static=y --build-ffmpeg-shared=y --compiler-flavors=multi --sandbox-ok=y --git-get-latest=y --high-bitdepth=y

Does anyone know what's wrong? The same call worked for three weeks now since I set up the nightly build...

I did a make "distclean" in the sandbox/win32/ffmpeg* directories. I even deleted them. No dice...

**Comment by konradci** [comment] 2016-07-29 14:12
Also since today, build fails during execution of  mingw-w64-build-3.6.7  with an error 

> Downloading cloog-.tar.gz... ./mingw-w64-build-3.6.7.local: line 482: exit: unable to download ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-.tar.gz: numeric argument required

which is caused by empty **cloog_ver** variable.

**Comment by lordcrc** [comment] 2016-07-29 17:40
It's due to an erroneous line being added in this commit https://github.com/rdp/ffmpeg-windows-build-helpers/commit/01559b194b227f4308a935c162f5a6d451426cde

**Comment by Collisionc** [comment] 2016-07-30 01:15
Yeah, remove the line:

https://github.com/rdp/ffmpeg-windows-build-helpers/commit/01559b194b227f4308a935c162f5a6d451426cde#diff-6aa78e200c567e3c5cf63806768b2be3R1552

and it will compile as normal

**Comment by nschlia** [comment] 2016-07-30 08:06
Anyone able to remove the line? I did that but it "git" restored during my nightly build when Jenkins did a git pull...

**Comment by lordcrc** [comment] 2016-07-30 09:25
Yes, just don't use git. Copy the cross_compile_ffmpeg.sh file to an empty directory, make the change and run it from there.

**Comment by nschlia** [comment] 2016-07-31 09:38
Yup. That works. The compile went through fine this night. Thanks for the hint!

**Comment by rdp** [comment] 2016-08-01 19:31
I think this is fixed now, ping me if otherwise, and sorry for the noise, trying to bump gcc but it isn't easy :|

**Closed by rdp** 2016-08-01 19:31 UTC
