### ISSUE TITLE
libmpg123 not found

### ISSUE THREAD

**Issue by upokojski** [rdp/ffmpeg-windows-build-helpers#552] opened 2021-03-13 16:24 UTC
Compiling on Ubuntu 20.04 fails with these messages:

checking for mpg123... nop
checking use of external mpg123 decoder... configure: no, libmpg123 not found

**Comment by Biswa96** [comment] 2021-03-13 16:27
Duplicate of previous issue https://github.com/rdp/ffmpeg-windows-build-helpers/issues/550

**Closed by Biswa96** 2021-03-13 16:27 UTC
