### ISSUE TITLE
ERROR: aom >= 1.0.0 not found using pkg-config

### ISSUE THREAD

**Issue by amol996** [rdp/ffmpeg-windows-build-helpers#332] opened 2018-07-17 08:43 UTC
Hi

https://github.com/rdp/ffmpeg-windows-build-helpers/issues/331

 Im building ffmpeg on Linux- ubuntu14.
ERROR: aom >= 1.0.0 not found using pkg-config   
[config.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/2200878/config.log)

ERROR: aom >= 1.0.0 not found using pkg-config                  

*************************ERROR*********************

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by AndCycle** [comment] 2018-07-18 09:19
which commit do you use for build ffmpeg?
this error already fixed in https://github.com/rdp/ffmpeg-windows-build-helpers/pull/330

there is not enough information from your post to determine where the problem is.

**Comment by rdp** [comment] 2018-07-23 14:52
Re open if still broken...

**Closed by rdp** 2018-07-23 14:52 UTC

**Comment by rodolfoap** [comment] 2018-09-07 14:38
A workaround is to run the build with sudo. Despite not appropriate, it helped us building.

**Comment by rdp** [comment] 2018-09-07 17:57
It works for me without sudo.  More information welcome! :)

**Comment by junkl-solbox** [comment] 2019-05-13 02:34
I meet same message at use tagged archive file (ex. https://aomedia.googlesource.com/aom/+archive/add4b15580e410c00c927ee366fa65545045a5d9.tar.gz)
but. solution is just use "git" (ex. git clone https://aomedia.googlesource.com/aom)
check "config/aom_version.h" after use cmake3.


PS.
The exact cause of the problem and the report to the aom are omitted because of the poor English.
