### ISSUE TITLE
GMP/ISL on Arch Linux with GMP 6.1.1

### ISSUE THREAD

**Issue by agressiv** [rdp/ffmpeg-windows-build-helpers#161] opened 2016-09-06 01:54 UTC
I cannot get ffmpeg to compile on Arch Linux.  GMP is 6.1.1, but the script says "configure: error: gmp library too old".  I've tried downgrading to GMP 6.0.0, but it didn't help.

  $ ../source/isl-0.12.2/configure --prefix=/home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/isl/isl-0.12.2-x86_64 --build=x86_64-pc-linux-gnu --enable-static --disable-shared --with-gmp-prefix=/home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gmp/gmp-6.0.0a-x86_64 --with-piplib=no --with-clang=no

This command fails because of "--with-gmp-prefix=/home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gmp/gmp-6.0.0a-x86_64."  If I remove that, I can compile isl manually, but I don't know how to "Resume".

Here was the error:

/usr/bin/ld: /home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gmp/gmp-6.0.0a-x86_64/lib/libgmp.a(fat_entry.o): relocation R_X86_64_32S against `__gmpn_cpuvec' can not be used when making a shared object; recompile with -fPIC
/home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gmp/gmp-6.0.0a-x86_64/lib/libgmp.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

I'm assuming this is what caused it to bomb.  I'm not really a developer, but I just tried to do some basic troubleshooting.

**Comment by rdp** [comment] 2016-09-06 02:19
is there any kind of config.log when it says "gmp too old"

**Comment by agressiv** [comment] 2016-09-06 02:31
configure:17333: error: gmp library too old

[config.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/455841/config.txt)

**Comment by rdp** [comment] 2016-09-06 02:46
that is some weird stuff:


configure:17330: gcc -o conftest -O3 -fomit-frame-pointer -malign-double
-fstrict-aliasing -ffast-math
-I/home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gmp/gmp-6.0.0a-x86_64/include
-L/home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gmp/gmp-6.0.0a-x86_64/lib
conftest.c -lgmp -lgmp  >&5
/usr/bin/ld:
/home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gmp/gmp-6.0.0a-x86_64/lib/libgmp.a(fat_entry.o):
relocation R_X86_64_32S against `__gmpn_cpuvec' can not be used when making
a shared object; recompile with -fPIC
/home/agressiv/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gmp/gmp-6.0.0a-x86_64/lib/libgmp.a:
error adding symbols: Bad value
collect2: error: ld returned 1 exit status

I will try a local recompile and see if I get it.
In the meantime I did bump the isl version recently, you could try
downgrading it again:

commit 02b25330f7faa325576d8fc47583ea0343884147
Author: rogerdpack <rogerpack2005@gmail.com>
Date:   Thu Jul 21 21:06:27 2016 -0600

    bump isl v in case it helps

diff --git a/patches/mingw-w64-build-3.6.7.local
b/patches/mingw-w64-build-3.6.7.local
index c9a5456..e657093 100755
--- a/patches/mingw-w64-build-3.6.7.local
+++ b/patches/mingw-w64-build-3.6.7.local
@@ -81,7 +81,7 @@ mpfr_release_ver='3.1.3'
 mpc_release_ver='1.0.3'
 binutils_release_ver='2.25.1'
 gmp_release_ver='6.0.0a'
-isl_release_ver='0.14'
+isl_release_ver='0.16.1'
 pthreads_w32_release_ver='2-9-1'

 ## Locations


but you'd have to manually run mingw-w64-build-3.6.7.local to see if it
makes a difference :|

**Comment by rdp** [comment] 2016-09-17 21:16
is this fixed now?

**Comment by jpham986** [comment] 2016-09-17 21:34
yes

**Closed** 2016-09-18 00:38 UTC

**Comment by agressiv** [comment] 2016-09-20 03:28
Still getting the exact same problem.

**Comment by jpham986** [comment] 2016-09-20 03:36
what problem is that ?

I'm using the build_locally_with_various_oiption_prompts.bat
which uses the cross_compile_ffmpeg.sh

**Comment by agressiv** [comment] 2016-09-20 13:29
The whole problem in this ticket above is unchanged.  If you build any Arch linux box, you can't run this cross compile script.  I've built fresh arch linux boxes with nothing else on them other than the components needed to compile this for troubleshooting purposes - I'm not running in Cygwin.  I can build on several flavors of ubuntu without difficulty, so I have a workaround, but I certainly wouldn't call this closed.

Incidentally, the isl package tries to download from: http://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/infrastructure and times out., I had to edit mingw-w64-build-3.6.7.local, prevent it from re-downloading the script over itself, and replace it with ftp.vim.org.  However, it didn't change anything, isl still refused to compile.

I see your ticket before, it was just a problem with isl _downloading_.  This ticket is a problem with isl _compiling_, but just on arch linux.

**Comment by jpham986** [comment] 2016-09-21 01:51
perhaps some of these files should be hosted on github in ffmpeg
that way we have everything in one place?
a lot of .edu site goes up and down

**Comment by rdp** [comment] 2016-09-25 04:08
Yeah maybe I just should just host them, easier, will think about it.
I think the problem is similar to this: http://stackoverflow.com/a/19768349
where somehow some dependency of gmp ends up being shared, then when
libgmp.a is used "as if static" later then things blow up.
I bumped the gmp version, see if it helps...

**Comment by jpham986** [comment] 2016-09-25 23:52
I vote for hosting on github, more control
or tar up the whole packages - the whole source code is not that big

**Comment by rdp** [comment] 2016-09-26 21:15
Yeah, if downloads give me a problem I will move them inline, too lazy
elsewise LOL
