### ISSUE TITLE
compilation error on default configuration

### ISSUE THREAD

**Issue by bala-smart** [rdp/ffmpeg-windows-build-helpers#511] opened 2020-11-30 07:52 UTC
I have issue on ffmpeg compilation
<img width="672" alt="error" src="https://user-images.githubusercontent.com/68465441/100582285-05d05f00-330f-11eb-8f6d-11e295de0706.png">

**Comment by LEETUMBRA** [comment] 2020-11-30 14:48
seems there is permission issues. Perhaps you can check the needed files or using root to deal with that, I used to change ownership, There might be better ways to compile.

**Comment by rdp** [comment] 2020-11-30 14:54
Yeah I haven't had luck with WSL on anything but the normal ext4
"home" mount, try there...

**Comment by LEETUMBRA** [comment] 2020-11-30 15:15
I also have found there are issues on gmp-6.2.0 when on WSL

**Comment by bala-smart** [comment] 2020-12-02 14:22
I am using root user with WSL, But no luck

**Comment by rdp** [comment] 2020-12-03 04:41
did you try building from home directory?

**Comment by bala-smart** [comment] 2020-12-04 10:53
Same error by compiling from homedrive
![error](https://user-images.githubusercontent.com/68465441/101155295-e9a12a80-364c-11eb-9096-1da7b2883b4a.png)

**Comment by rdp** [comment] 2020-12-05 02:01
You can't compile it from /mnt it had to be from you Linux home directory.
Or you could try a virtualbox...
Good luck!

On Friday, December 4, 2020, bala-smart <notifications@github.com> wrote:
> Same error by compiling from homedrive
> <
https://ci5.googleusercontent.com/proxy/4J_IA2UvtZcE6aunif8t_q6HGy88rPoNjS0bMbTgeD1qwBB9jc5WieEuMS3_AwlL_5h1dlTAdNVLCdwdTt9Tr0CymfplWyD3Ol-_twXoWxcZog4yrP5IyrbpInFHBnDmnp_q4reCLp535no_NHPvLVOYIoQuaaiM=s0-d-e1-ft#https://user-images.githubusercontent.com/68465441/101155295-e9a12a80-364c-11eb-9096-1da7b2883b4a.png
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/9MZHyC4xffoOe-_x2VBURnGE4XHeLKPESApez3lHGCRvUHji6KUHbSoKSXSpGa-vdnzJ9vGK_Og2H_fjlgkpkqHJEOcadzziFAmTRit_dzLR2gRy2MRT0uneeb6HS2FREZ1vdAYWxnZVDYmrzb-4eAVa4b6uFV7wJYEc1RkgfHLAP6Z6Wc0R0dwhkaxv8eD5xcLeNs_lMhy-JY3Itr7Wnp7PjHN62zuGdj9YN43oVQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUC5YV7B6A5CT2MNWZ3STC5RZA5CNFSM4UHGLHG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFQD6TDQ.gif>

**Comment by bala-smart** [comment] 2020-12-15 06:38
I am getting below error on compiling on linux machine
![ffmpeg_error](https://user-images.githubusercontent.com/68465441/102180023-33e89e00-3ece-11eb-8940-d5ac8dbec109.png)

**Comment by rdp** [comment] 2020-12-16 05:10
What version of Linux?

On Monday, December 14, 2020, bala-smart <notifications@github.com> wrote:
> I am getting below error on compiling on linux machine
> <
https://ci6.googleusercontent.com/proxy/5s-ttua4nVzQgNoISOLoSDM6u5KYGnJrzxRx7BH6GqJMvCN6V_mCemZAjdYe64YIOgufP0uWhJXlmsSzqjfyMPzchwmpdRz_7EpfLm59kNpKbqhLh1S2dT3-FHVliCkQC5YX6_YJnlNbRhAqyaQNN3S9w4mmTQhq=s0-d-e1-ft#https://user-images.githubusercontent.com/68465441/102180023-33e89e00-3ece-11eb-8940-d5ac8dbec109.png
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/_tTFcsxsfRRD2fhCCKVNpyBXcT1YEu5vMMCImBPaS_y8QqP_dzxhEGr1AyDEBv_mjzJe6hA1OnMbqtL3gYqe8MHJsJqXQ78DdO7ab4vYERC-kkOk9O2fZoJqnAaGigs_tJZXBBvyBWyG1EvqUeaynKUmYNVeyhl9YKSNRwz760JcriDji3gRX_dCVnIUBgAjOQqplRGItiTHnQtx2xwMe0EjTmXtskF8lkRRof0x8g=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUDFHBYKFXRHYQPI3RLSU376LA5CNFSM4UHGLHG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFRUSARA.gif>

**Comment by bala-smart** [comment] 2020-12-17 15:52
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

**Comment by rdp** [comment] 2020-12-18 05:17
Maybe try a newer linux?

For followers, message was gcc undefined reference zstd_getframecontentsize

**Comment by rdp** [comment] 2021-03-19 03:12
Closing assuming was caused by old linux version.  reopen if present in newer versions, thanks!

**Closed by rdp** 2021-03-19 03:12 UTC
