### ISSUE TITLE
Installing binutils fails under windows

### ISSUE THREAD

**Issue by IvanNMz** [rdp/ffmpeg-windows-build-helpers#206] opened 2017-02-22 14:34 UTC
After running native_build\windows\build_locally_with_various_option_prompts.bat  script fails at the following step: [7/54] Installing binutils...

Log file ending:

make[4]: Entering directory '/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld'
/bin/sh ../../../source/binutils-2.26.1/ld/../ylwrap ../../../source/binutils-2.26.1/ld/ldlex.l lex.yy.c ../../../source/binutils-2.26.1/ld/ldlex.c -- flex  
gcc -DHAVE_CONFIG_H -I. -I../../../source/binutils-2.26.1/ld  -I. -I../../../source/binutils-2.26.1/ld -I../bfd -I../../../source/binutils-2.26.1/ld/../bfd -I../../../source/binutils-2.26.1/ld/../include  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=FALSE -DELF_SHLIB_LIST_OPTIONS=FALSE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -MT ldlex-wrapper.o -MD -MP -MF .deps/ldlex-wrapper.Tpo -c -o ldlex-wrapper.o ../../../source/binutils-2.26.1/ld/ldlex-wrapper.c 
mv -f .deps/ldlex-wrapper.Tpo .deps/ldlex-wrapper.Po
/bin/sh ./libtool --tag=CC   --mode=link gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=FALSE -DELF_SHLIB_LIST_OPTIONS=FALSE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2  -Wl,--stack,12582912 -o ld-new.exe ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o ei386pe.o deffilep.o pe-dll.o ../bfd/libbfd.la ../libiberty/libiberty.a  
libtool: link: gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=FALSE -DELF_SHLIB_LIST_OPTIONS=FALSE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -Wl,--stack -Wl,12582912 -o ld-new.exe ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o ei386pe.o deffilep.o pe-dll.o  ../bfd/.libs/libbfd.a -L/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/zlib -lz ../libiberty/libiberty.a
ldlex-wrapper.o: In function `yylex':
/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld/../../../source/binutils-2.26.1/ld/ldlex.c:3342: undefined reference to `yywrap'
ldlex-wrapper.o: In function `input':
/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld/../../../source/binutils-2.26.1/ld/ldlex.c:3645: undefined reference to `yywrap'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:1088: ld-new.exe] Error 1
make[4]: Leaving directory '/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld'
make[3]: *** [Makefile:1713: install-recursive] Error 1
make[3]: Leaving directory '/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld'
make[2]: *** [Makefile:1877: install] Error 2
make[2]: Leaving directory '/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32/ld'
make[1]: *** [Makefile:7228: install-ld] Error 2
make[1]: Leaving directory '/cygdrive/c/Temp/FFmpeg_test/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/pkgs/binutils/build/i686-w64-mingw32'
make: *** [Makefile:2244: install] Error 2

**Comment by rdp** [comment] 2017-03-09 17:03
appears to be a dupe of #201 continuing conversation there...

**Closed by rdp** 2017-03-09 17:03 UTC
