### ISSUE TITLE
Unknown option "--enable-libsvthevc" with building ffmpeg

### ISSUE THREAD

**Issue by BlackScreen** [rdp/ffmpeg-windows-build-helpers#564] opened 2021-04-28 15:13 UTC
```
configuring ffmpeg_git_pre_x264_with_fdk_aac (/home/USER/ffmpeg/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_pre_x264_with_fdk_aac) as $ PKG_CONFIG_PATH=/home/USER/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/USER/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/USER/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg  --enable-libopenh264 --enable-liblensfun  --enable-libvmaf --enable-libsrt --enable-demuxer=dash --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --enable-avresample --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/USER/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --enable-decklink --disable-libx264
all touch files already_configured* touchname= already_configured_0292dbcb3158cde5f0fc1c30e78a2a83-
config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/USER/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-demuxer=dash --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --enable-avresample --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/USER/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --enable-decklink --disable-libx264 ./configure
Unknown option "--enable-libsvthevc".
See ./configure --help for available options.
failed configure ffmpeg_git_pre_x264_with_fdk_aac
```

**Comment by rdp** [comment] 2021-05-01 19:45
Is this still there?

**Comment by nschlia** [comment] 2021-05-01 21:20
Still around:

23:18:19 Unknown option "--enable-libsvthevc".
23:18:19 See ./configure --help for available options.
23:18:19 failed configure ffmpeg_git_with_fdk_aac_shared
23:18:19 Build step 'Shell ausführen' marked build as failure

**Comment by nschlia** [comment] 2021-05-01 21:24
There's an extra hint at the beginning:

23:18:19 fetched no code changes, not forcing reconfigure for that...
23:18:19 error: cannot open path '../SVT-HEVC_git/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch'; File not found
23:18:19 error: Applying patch failed: doc/general_contents.texi:259
23:18:19 error: doc/general_contents.texi: Could not apply patch
23:18:19 configuring ffmpeg_git_with_fdk_aac_shared (/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/win64/ffmpeg_git_with_fdk_aac_shared) as $ PKG_CONFIG_PATH=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg  --enable-libopenh264 --enable-liblensfun  --enable-libvmaf --enable-libsrt --enable-demuxer=dash --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-shared --disable-static --prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/win64/ffmpeg_git_with_fdk_aac_shared --enable-nonfree --enable-libfdk-aac --enable-decklink 
23:18:19 all touch files already_configured* touchname= already_configured_58431b62659de148cce07872dbfe1dd5-
23:18:19 config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-demuxer=dash --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-shared --disable-static --prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/win64/ffmpeg_git_with_fdk_aac_shared --enable-nonfree --enable-libfdk-aac --enable-decklink ./configure

23:18:19 Unknown option "--enable-libsvthevc".
23:18:19 See ./configure --help for available options.
23:18:19 failed configure ffmpeg_git_with_fdk_aac_shared

**Comment by nschlia** [comment] 2021-05-07 05:30
Anything new on this? My builds keep failing with exactly this problem:
```
23:18:19 error: cannot open path '../SVT-HEVC_git/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch'; File not found
23:18:19 error: Applying patch failed: doc/general_contents.texi:259
23:18:19 error: doc/general_contents.texi: Could not apply patch
```

**Comment by timothymowens** [comment] 2021-05-09 18:36
The issue is a different patch has been created for FFmpeg v4.4:

https://github.com/OpenVisualCloud/SVT-HEVC/commit/b5587b09f44bcae70676f14d3bc482e27f07b773

The current cross_compile_ffmpeg.sh script is attempting to pull the patch for previous FFmpeg releases that does not exist for v4.4.

The cross_compile_ffmpeg.sh script needs to be updated to instead pull this patch:

- n4.4-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

Replace this line in build_ffmpeg():

`git apply "../SVT-HEVC_git/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch"`

With this:

`git apply "../SVT-HEVC_git/ffmpeg_plugin/n4.4-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch`

**Comment by timothymowens** [comment] 2021-05-10 20:52
> @timothymowens
> Maybe you can make a pull request to fix this?

Just submitted a pull request.

**Comment by BlackScreen** [comment] 2021-05-11 13:29
> @BlackScreen Try it now. My PR was merged.

I will later, thanks!

**Comment by BlackScreen** [comment] 2021-05-11 17:18
Working for me, thanks.
The only thing I noticed is, that the sandbox-folder with the fdk-acc-build changed from "ffmpeg_git_with_fdk_aac" to "ffmpeg_git_with_fdk_aac_master".
This is not a problem of course, just a thing I noticed. :)

**Comment by nschlia** [comment] 2021-05-16 20:35
Build OK now, can be closed I'd say. Thanks for the fix!

**Comment by echoxxzz** [comment] 2021-07-17 02:06
I tried building ffmpeg today and I'm still getting this exact error message.

**Comment by kusaanko** [comment] 2021-07-22 09:36
@echoxxzz This will be fixed.
https://github.com/OpenVisualCloud/SVT-HEVC/pull/608

**Comment by kusaanko** [comment] 2021-07-22 17:56
Hi @echoxxzz , the pr was merged and is there still the same error?

**Comment by echoxxzz** [comment] 2021-07-23 17:07
> Hi @echoxxzz , the pr was merged and is there still the same error?

I did a 'git pull' but it says I'm already up to date so I can't test. Is there something I'm doing wrong? I must admit I'm not a git expert.

**Comment by kusaanko** [comment] 2021-07-23 17:11
> > Hi @echoxxzz , the pr was merged and is there still the same error?
> 
> I did a 'git pull' but it says I'm already up to date so I can't test. Is there something I'm doing wrong? I must admit I'm not a git expert.

You don't have to pull. The pr is not for this repository. Please try to build as is.

**Comment by kusaanko** [comment] 2021-07-23 17:19
@echoxxzz If you still have the same error, please try clean and rebuild.

**Comment by echoxxzz** [comment] 2021-07-23 20:41
> @echoxxzz If you still have the same error, please try clean and rebuild.

It works now without the "--ffmpeg-git-checkout-version=n4.4" option.

**Comment by rdp** [comment] 2021-10-22 03:37
Closing no feedback, feel free to reopen!

**Closed by rdp** 2021-10-22 03:37 UTC

**Comment by dp289m** [comment] 2023-11-21 04:45
same error with 6.1 I guess...

**Comment by NobleRonin** [comment] 2023-11-28 14:29
I thought I was insane, I also got the error
`ffmpeg version 2023-11-27-git-0ea9e26636-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 32.100 / 58. 32.100
  libavcodec     60. 35.100 / 60. 35.100
  libavformat    60. 18.100 / 60. 18.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 13.100 /  9. 13.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
Unrecognized option '-enable-svtav1'.
Error splitting the argument list: Option not found`

Clearly --enable-svtav1 exists (it's in the list)
