### ISSUE TITLE
LibRubberband not found using pkg-config

### ISSUE THREAD

**Issue by Lazinezz** [rdp/ffmpeg-windows-build-helpers#203] opened 2017-02-10 11:53 UTC
Hi,
    had this issue when trying to compile ffmpeg "LibRubberband not found using pkg-config" using mingw64 version 5.0.1 and gcc 6.3.0.., sorry as im a newbie and so i ponder inside the "ffmpeg_git_with_fdk_aac" folder and open up "configure" n found....

4837    # Set image base >4GB for extra entropy with HEASLR
4838    add_ldexeflags -Wl,--image-base,0x140000000
4839    append SHFLAGS -Wl,--image-base,0x180000000

Then i delete line "4838" , looks like this,

4837    # Set image base >4GB for extra entropy with HEASLR
4839    append SHFLAGS -Wl,--image-base,0x180000000

saves changes and rerun ./cross_compile_ffmpeg.sh and everything went smooth...ffmpeg compiled without errors, n now i have a working 64bit ffmpeg.exe built using mingw64 version 5.0.1 and gcc 6.3.0.

So my question is, why do after i deleted line 4838 ( workaround solution found from other link while browsing) only can ffmpeg compile without errors??

lol, pardon my longwinded post and thank you very much. =]

**Comment by rdp** [comment] 2017-02-10 14:49
it shouldn't be using gcc 6.3.0 anymore care to nuke your sandbox and try again?

**Comment by rdp** [comment] 2017-02-10 14:55
oops that's a local gcc 6.3.0? Which configure file is this?

**Comment by Lazinezz** [comment] 2017-02-10 15:51
thx for replying, yes i manually set ur cross compile sh and 3.6.7 to download mingw64 5.0.1 n gcc 6.3.0, so if it means local then local it is...n its the "configure" from  "ffmpeg_git_with_fdk_aac" folder.

**Comment by Lazinezz** [comment] 2017-02-10 16:00
maybe i forgot to mention that librubberband enabled just fine when compiling ffmpeg, after i deleted that particular line in ffmpeg's configure file.

**Comment by rdp** [comment] 2017-02-10 20:34
What tipped you off this might be the problem?

**Comment by Lazinezz** [comment] 2017-02-11 09:43
Hi,
    This link https://trac.ffmpeg.org/ticket/5895 ,it was reported by zeranoe n so i tried his workaround, it works...bcos i had the same overflow issues as him too,librubberband,libsnappy etc

**Comment by maki-chan** [comment] 2017-02-28 21:10
I can confirm that it helps to remove the LDFLAGS `-Wl,--image-base,0x140000000`, though I had to do it for ffmpeg twice (it compiles once without and once with fdk_aac) and I was not able to build x264 with libav successfully.

**Comment by hydra3333** [comment] 2017-03-05 11:35
I see rdp reported it here fpr gcc 6.3.0 ...
https://sourceforge.net/p/mingw-w64/mailman/message/35643081/

**Comment by rdp** [comment] 2017-03-06 17:18
Yeah though I'm doubting now it is a gcc error, more like a link time
failure...

**Comment by schmidthubert** [comment] 2017-03-06 21:49
Why go through all the hassle with that gcc 6.x bugger when a current gcc 7.x snapshot will work just fine even with rubberband, zimg and snappy options ...  All you have to do is change libiconv to the recent 2017 build version 1.15 and your script will work very well ... Good luck! :-)

**Comment by Lazinezz** [comment] 2017-03-07 02:54
Tried that already, same result...tried compiling with gcc 7 snapshot, the same issue occured "rubberband not found" error, had to delete that ldflag in order to make it work haish... i wonder why i wonder how lol

**Comment by hydra3333** [comment] 2017-03-07 09:49
just wondering, since you didn't mention it, did you also "change libiconv to the recent 2017 build version 1.15" ?

**Comment by rdp** [comment] 2017-03-07 17:53
not yet, haven't quite figured out how to do gcc 4.7 yet

**Comment by schmidthubert** [comment] 2017-03-09 08:00
@Lazinezz: you have to nuke your complete sandbox and start fresh with a patch which is known to google for about a year now, even rdp [knows about it](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69506)! I don't know why he's not fixing his script if everyone here is so keen as to have gcc >= 6.2+ working even if gcc 6+7 are *NOT* producing the fastest code, at least not for me (gcc 5.4.0 is). There's a lot of hardcoded assembler already in it, so no compiler will speed it up any further ... Anyway, here's the 2 patches (here for the gcc 7 snapshot), you need to rebuild your gcc ...

============================================================
--- source/libstdc++-v3/config/os/mingw32/os_defines.h.orig	Thu Jan 01 01:00:00 1970
+++ source/libstdc++-v3/config/os/mingw32/os_defines.h	Thu Jan 01 01:00:00 1970
@@ -73,6 +73,7 @@
 
 #ifdef __x86_64__
 #define _GLIBCXX_LLP64 1
+#define _GLIBCXX_USE_WEAK_REF 0
 #endif
 
 // See libstdc++/59807

============================================================
--- source/libstdc++-v3/config/os/mingw32-w64/os_defines.h.orig	Thu Jan 01 01:00:00 1970
+++ source/libstdc++-v3/config/os/mingw32-w64/os_defines.h	Thu Jan 01 01:00:00 1970
@@ -76,6 +76,7 @@
 
 #ifdef __x86_64__
 #define _GLIBCXX_LLP64 1
+#define _GLIBCXX_USE_WEAK_REF 0
 #endif
 
 // Enable use of GetModuleHandleEx (requires Windows XP/2003) in

============================================================
Further reading:
https://forum.doom9.org/showthread.php?t=173761
https://github.com/Alexpux/MINGW-packages/pull/1588
https://github.com/gcc-mirror/gcc/commit/40c727c8722ab47a821e2fe371f1b6b96be0200dhttps://github.com/Alexpux/MINGW-packages/pull/1722
https://github.com/Alexpux/MINGW-packages/commit/ecf5a0d372ebe7bc55b52859c26b26a337b556c7
...
Just to name a few ... Now good luck again! :-)

**Comment by DeadSix27** [comment] 2017-03-09 09:20
@rdp Ye I implemented that patch already, also updating a lot of deps, which is step one in the mp replacement i mentioned a month back or so.

**Comment by Lazinezz** [comment] 2017-03-09 11:11
schmidthubert,
thx much..i think ive tried that with gcc 6.2 sometime ago but no good, havent tried with ggc 7 tho..will try it with gcc 7 now n update the result later.

**Comment by DeadSix27** [comment] 2017-03-09 18:13
@rdp btw, are you on IRC or Discord or something? If not you can visit mine, just say so and I'll invite you. Would make this a bit easier, I do not really want to spam the issue tracker with ideas.

**Comment by rdp** [comment] 2017-03-09 18:44
If you want to spam "just me" then create a new issue, no IRC ATM.

**Comment by DeadSix27** [comment] 2017-03-09 19:03
@rdp alright, ill see to it later, or maybe just open an issue on my fork and link it.

**Comment by Lazinezz** [comment] 2017-03-10 04:01
ok update,
rebuild with mingw64 v5.0.1 n gcc 7 snapshot with "define _GLIBCXX_USE_WEAK_REF 0" patch applied resulting with smooth sailing...no errors occured at all, no rubberband not found,libsnappy,sdl2 errors no nothing occured at all. thx much schmidthubert, appreciate it. just wondering if theres any side effect with the patch applied, but will test ffmpeg n see if theres any.

**Comment by DeadSix27** [comment] 2017-03-10 11:50
@Lazinezz yep, on gcc 6.3.0 too, about the side effects, I do not know either. according to all the people that did it, not, but  thats not enough i guess.

**Comment by rdp** [comment] 2017-03-10 17:16
So gcc 7 still needs that WEAK_REF thing?

**Comment by schmidthubert** [comment] 2017-03-10 22:58
@Lazinezz: that "#define _GLIBCXX_USE_WEAK_REF 0" is *THE DEFAULT* for other OS's already! Just try the following on ie. the unpacked gcc7 source package and see what you get:
me@console:/tmp# grep -nr _GLIBCXX_USE_WEAK_REF *

To keep things simple here: it's just a static linking problem / (name-)"collision" of sort .. Other than that, and if you really must know, "weak ref" on google will produce detailed explanations but personally I've got better things to do with my time than reading up on all of them ... ;-) So here's just one:

http://stackoverflow.com/questions/21092601/is-pthread-in-glibc-so-implemented-by-weak-symbol-to-provide-pthread-stub-functi

You can even find "Weak Reference" on wikipedia if you must .... 

HTH!

**Comment by rdp** [comment] 2017-04-11 15:55
so you think 5.4.0 is the "best" version here? hmm

**Comment by schmidthubert** [comment] 2017-04-11 16:54
Yes. But 4.9.4 is stable as well but there's no further snapshots currently. And 5.4.0 doesn't get "big" diffs now anymore but gcc6 certainly gets more stuff backported from gcc7. But for THIS project I prefer something which has been around longer. Plus for me most of the times I get ~2-5 fps out of some transcode . I know it's not much and doesn't matter anymore with the GTX's fixed functions and cuvid accel now but I'm just saying. :) More important than that for YOU maybe the overall compile time of the build script? I must admit I've been a lazy git so far as to this and didn't take the time to measure this myself, maybe you should then. :) Speaking of gcc versions here: the mingw-*.local script should really be made more flexible as to the gcc version. It should support gcc snapshot downloads as well if anyone wants to try them out ...

**Comment by rdp** [comment] 2017-04-11 23:18
Yeah I didn't actually write those, that's my excuse :)

**Comment by schmidthubert** [comment] 2017-04-12 10:48
You should freeze this to maybe mingw 5.0.2 + bzip 2.28 + gcc 4.9.4/5.4.0 => stable and then start your own from there. Your "excuse" for writing your own mingw*.local script or doing a fork should be that zeranoe does NOT provide his CURRENT script(s) and we don't wanna be stuck here and fiddle with his old stuff forever! That way this "project" should progress much better ... :beer:

**Comment by schmidthubert** [comment] 2017-04-16 00:53
This issues should be closed because this patch is already part of MSYS2 for like 3 months:

https://sourceforge.net/projects/msys2/
https://github.com/Alexpux/MSYS2-packages/blob/master/mingw-w64-cross-gcc/PKGBUILD
:information_desk_person:

**Comment by hydra3333** [comment] 2017-04-16 09:58
a newbie question, for clarity, 
- does that mean that building mingw from git contain the equivalent of a weak ref's patch ?
- eg invoking the mingw build script with these commandline parameters (such as git") ?
`local zeranoe_script_options="--clean-build --disable-shared --default-configure  --pthreads-w32-ver=2-9-1 --cpu-count=$gcc_cpu_count --mingw-w64-ver=git --gcc-ver=6.3.0"`

**Comment by DeadSix27** [comment] 2017-04-16 10:04
@hydra3333 the weak refs patch is not in the source no.
see: https://gcc.gnu.org/svn/gcc/trunk/libstdc++-v3/config/os/mingw32-w64/os_defines.h
It has to be patched in as of yet, maybe they add it with gcc 7? idk

**Comment by rdp** [comment] 2017-07-06 00:36
apparently still not fixed (without patch anyway) in 7.1.0 FWIW...

**Comment by rdp** [comment] 2017-07-20 15:45
FWIW this patch:
https://github.com/gcc-mirror/gcc/commit/40c727c8722ab47a821e2fe371f1b6b96be0200d
is in the source now.  I think it missed 7.1.0 [?]

**Comment by rdp** [comment] 2017-07-25 14:13
OK finally fixed now, thanks!

**Closed by rdp** 2017-07-25 14:13 UTC
